server:
  port: 8420
  servlet:
    context-path: /hail-hydra
spring:
  #druid
  datasource:
    username: root
    password: yt19960616..
    url: jdbc:mysql://localhost:3306/hail-hydra?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 20
    initial-size: 5
    min-idle: 5
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'X'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false

  #redis
  redis:
    connection-timeout: 5000
    password: yt19960616..
    database: 0
    port: 6379
    jedis:
      pool:
        max-idle: 200
        min-idle: 10
        max-active: 1024
        max-wait: 10000
    host: 127.0.0.1
    ssl: false
    timeout: 10000

#myabtis
mybatis:
  mapper-locations: mapper/*.xml
logging:
  config: classpath:logback-spring.xml
